<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="FB_Math" Id="{6fbab0f8-a7af-456d-8d51-f26ee1045dbf}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Math
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="AddTwo" Id="{7197c489-6d7a-4f1e-8c2b-9cccebb0429f}">
      <Declaration><![CDATA[METHOD AddTwo : REAL
VAR_INPUT
	Real1 :REAL;
	Real2 :REAL;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[

AddTwo := Real1 + Real2;

AddTwo := Real1 + Real2;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Math">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="FB_Math.AddTwo">
      <LineId Id="11" Count="0" />
      <LineId Id="5" Count="0" />
      <LineId Id="12" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>